PreCommit:
  BundlerAudit:
    enabled: true
  RuboCop:
    enabled: true
    on_warn: fail
  Fasterer:
    enabled: true
  RailsSchemaUpToDate:
    enabled: true
  RailsBestPractices:
    enabled: true
  Bullet:
    enabled: true
PrePush:
  Brakeman:
    enabled: true
