AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'chef/**/*'

LineLength:
  Enabled: true
  Max: 120
Style/Documentation:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - app/admin/**/*
