AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'

LineLength:
  Enabled: true
  Max: 120
Style/Documentation:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
