default: &default
  adapter:  postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV["DB_LOGIN"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: worker_development

test:
  <<: *default
  database: worker_test

production:
  <<: *default
  database: worker_production
